#pragma once
#include "TransformComponent.h"
#include "ecs/Entity.h"
#include "lib/VQBuffer.h"

class PhongRenderSystemInstanced;
// component generated by phong render system
struct PhongRenderSystemInstancedComponent : IComponent
{
    // TODO: should textureID be a separate texture component?
    int textureID;  // offset used to index into global texture array
    unsigned int instanceID; // use this to index into instance buffer array
    std::array<VQBuffer, NUM_FRAME_IN_FLIGHT>* instanceBuffer; // instance buffer for each frame
    PhongRenderSystemInstanced* parent = nullptr;
    void FlagAsDirty(Entity* owner);

};
